# Basic Data Exploration and Cleaning using Pandas
**Dataset:** Myntra Combined Dataset (`Combined_dataset.csv`)  
**Records:** 1000 products | 24 columns | 97 product categories  

**Steps:**
1. Load CSV into a Pandas DataFrame
2. Explore data (head/tail, shape, columns, dtypes)
3. Handle missing values (identify, fill/drop)
4. Perform basic operations (filter rows, select columns)
5. Remove duplicates
6. Create derived column (`total_amount = initial_price * discount / 100`)
7. Save cleaned dataset + print summary report

## Step 1: Import Libraries and Load Dataset

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\Lenovo\Downloads\archive\Combined_dataset.csv")

print('Dataset loaded successfully!')
print(f'Shape: {df.shape[0]} rows x {df.shape[1]} columns')

Dataset loaded successfully!
Shape: 1000 rows x 24 columns

## Step 2: Explore the Data

In [3]:
print('HEAD (first 5 rows)')
df[['product_id','title','product_description','rating','ratings_count','initial_price','discount','final_price','category']].head()

HEAD (first 5 rows)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",bath-robe

In [4]:
print('TAIL (last 5 rows)')
df[['product_id','title','product_description','rating','ratings_count','initial_price','discount','final_price','category']].tail()

TAIL (last 5 rows)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",yoga-mats

In [5]:
print(f'Number of rows    : {df.shape[0]}')
print(f'Number of columns : {df.shape[1]}')

Number of rows    : 1000
Number of columns : 24

In [6]:
print('--- COLUMNS ---')
for i, col in enumerate(df.columns, 1):
    print(f'  {i:2}. {col}')

--- COLUMNS ---
   1. product_id
   2. title
   3. product_description
   4. rating
   5. ratings_count
   6. initial_price
   7. discount
   8. final_price
   9. currency
  10. images
  11. delivery_options
  12. product_details
  13. breadcrumbs
  14. product_specifications
  15. amount_of_stars
  16. what_customers_said
  17. seller_name
  18. sizes
  19. videos
  20. seller_information
  21. variations
  22. best_offer
  23. more_offers
  24. category

In [7]:
print('DATA TYPES')
print(df.dtypes)

DATA TYPES
product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [8]:
print('--- STATISTICAL SUMMARY ---')
df[['rating','ratings_count','initial_price','discount']].describe()

--- STATISTICAL SUMMARY ---

          rating  ratings_count  initial_price    discount
count  1000.0000    1000.000000     1000.00000  879.000000
mean      3.6215      76.691000     2723.24100   53.503982
std       1.3744     241.114263     2408.69736   18.029201
min       0.0000       0.000000      249.00000    1.000000
25%       3.7000       7.000000     1399.00000   44.000000
50%       4.1000      17.000000     1999.00000   56.000000
75%       4.3000      58.000000     3299.00000   66.000000
max       5.0000    4441.000000    22199.00000   88.000000

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [10]:
print('TOP 10 CATEGORIES')
print(df['category'].value_counts().head(10))

TOP 10 CATEGORIES
category
tops            122
dresses         100
shirts           97
jeans            57
sports-shoes     51
tshirts          39
earrings         34
sweaters         34
jackets          29
casual-shoes     23
Name: count, dtype: int64

## Step 3: Handle Missing Values

In [11]:
print(' MISSING VALUES PER COLUMN')
missing = df.isnull().sum()
pct = (missing / len(df) * 100).round(1)
report = pd.DataFrame({'Missing Count': missing, 'Missing %': pct})
print(report[report['Missing Count'] > 0])
print(f'\nTotal missing values: {missing.sum()}')

 MISSING VALUES PER COLUMN
                     Missing Count  Missing %
discount                       121       12.1
what_customers_said            573       57.3
seller_name                    301       30.1
videos                         781       78.1
seller_information             301       30.1
variations                     562       56.2

Total missing values: 2639

In [12]:
df = df.assign(discount=df['discount'].fillna(df['discount'].median()))
print(f'discount: filled 121 missing values with median = {df["discount"].median()}%')

df = df.assign(seller_name=df['seller_name'].fillna('Unknown Seller'))
print('seller_name: filled 301 missing values with "Unknown Seller"')

df = df.assign(what_customers_said=df['what_customers_said'].fillna('No Reviews'))
print('what_customers_said: filled 573 missing values with "No Reviews"')

discount: filled 121 missing values with median = 56.0%
seller_name: filled 301 missing values with "Unknown Seller"
what_customers_said: filled 573 missing values with "No Reviews"

In [13]:
cols_to_drop = ['videos', 'seller_information', 'variations']
df.drop(columns=cols_to_drop, inplace=True)
print(f'Dropped columns: {cols_to_drop}')

before = len(df)
df.dropna(inplace=True)
print(f'\nRows before dropna : {before}')
print(f'Rows after dropna  : {len(df)}')
print(f'Missing remaining  : {df.isnull().sum().sum()}')

Dropped columns: ['videos', 'seller_information', 'variations']

Rows before dropna : 1000
Rows after dropna  : 1000
Missing remaining  : 0

## Step 4: Basic Operations — Filter Rows & Select Columns

In [14]:
df['final_price'] = df['final_price'].str.replace(r'[₹",\s]', '', regex=True).astype(float)
print('final_price cleaned. Sample:')
print(df[['title','initial_price','discount','final_price']].head(5))

final_price cleaned. Sample:
            title  initial_price  discount  final_price
0     Lino Perros           3995      58.0       3995.0
1  Tommy Hilfiger           2899      35.0       2899.0
2           Lavie           2999      65.0       2999.0
3          F Gear           1675      52.0       1675.0
4       MYTRIDENT           2899      17.0       2899.0

In [15]:
top_rated = df[df['rating'] >= 4.0]
print(f'Well-rated products (rating >= 4.0): {len(top_rated)}')
print(top_rated[['title','category','rating','final_price']].head(6))

Well-rated products (rating >= 4.0): 615
            title              category  rating  final_price
1  Tommy Hilfiger             backpacks     4.5       2899.0
2           Lavie             backpacks     4.4       2999.0
3          F Gear             backpacks     4.4       1675.0
4       MYTRIDENT             bath-robe     4.7       2899.0
5             H&M  bathroom-accessories     4.5       1399.0
6      AVI Living           bath-towels     4.0       1399.0

In [16]:
high_discount = df[df['discount'] >= 60]
print(f'Products with 60%+ discount: {len(high_discount)}')
print(high_discount[['title','category','initial_price','discount','final_price']].head(6))

Products with 60%+ discount: 395
            title     category  initial_price  discount  final_price
2           Lavie    backpacks           2999      65.0       2999.0
6      AVI Living  bath-towels           1399      65.0       1399.0
11         Arrabi    bedsheets           3329      74.0        865.0
12     BELLA CASA    bedsheets           1499      73.0        404.0
13          ROMEE    bedsheets           3499      65.0       3499.0
16  DREAM WEAVERZ    bedsheets           2599      78.0       2599.0

In [17]:
backpacks = df[df['category'] == 'backpacks']
print(f'Backpacks: {len(backpacks)} products')
print(backpacks[['title','rating','initial_price','final_price']].head(5))

Backpacks: 4 products
            title  rating  initial_price  final_price
0     Lino Perros     3.8           3995       3995.0
1  Tommy Hilfiger     4.5           2899       2899.0
2           Lavie     4.4           2999       2999.0
3          F Gear     4.4           1675       1675.0

In [24]:
key_cols = ['product_id','title','product_description','category',
            'rating','ratings_count','initial_price','discount','final_price','seller_name']
selected = df[key_cols]
print('Selected Key Columns')
selected.head()

Selected Key Columns

,product_id,title,product_description,category,rating,ratings_count,initial_price,discount,final_price,seller_name
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,backpacks,3.8,15,3995,58.0,3995.0,Unknown Seller
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,backpacks,4.5,67,2899,35.0,2899.0,Unknown Seller
2,17633752,Lavie,Aries Women Pink Mini Backpack,backpacks,4.4,226,2999,65.0,2999.0,Unknown Seller
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,backpacks,4.4,1052,1675,52.0,1675.0,Unknown Seller
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,bath-robe,4.7,12,2899,17.0,2899.0,Unknown Seller

## Step 5: Remove Duplicates

In [25]:
print(f'Total rows        : {len(df)}')
print(f'Duplicate rows    : {df.duplicated().sum()}')
print(f'Duplicate product_ids: {df["product_id"].duplicated().sum()}')

Total rows        : 1000
Duplicate rows    : 0
Duplicate product_ids: 0

In [26]:
df.drop_duplicates(inplace=True)
print(f'Rows after removing duplicates:{len(df)}')

Rows after removing duplicates:1000

## Step 6: Create Derived Column — total_amount

In [27]:
df['total_amount'] = (df['initial_price'] * df['discount'] / 100).round(2)

print('total_amount column added (amount saved in ₹)')
df[['title','initial_price','discount','final_price','total_amount']].head(8)

total_amount column added (amount saved in ₹)

            title  initial_price  discount  final_price  total_amount
0     Lino Perros           3995      58.0       3995.0       2317.10
1  Tommy Hilfiger           2899      35.0       2899.0       1014.65
2           Lavie           2999      65.0       2999.0       1949.35
3          F Gear           1675      52.0       1675.0        871.00
4       MYTRIDENT           2899      17.0       2899.0        492.83
5             H&M           1399      56.0       1399.0        783.44
6      AVI Living           1399      65.0       1399.0        909.35
7         My Room           2999      54.0       2999.0       1619.46

In [28]:
print('Discount Saved (total_amount) Statistics')
print(f'Min  savings : ₹{df["total_amount"].min():,.2f}')
print(f'Max  savings : ₹{df["total_amount"].max():,.2f}')
print(f'Mean savings : ₹{df["total_amount"].mean():,.2f}')
print(f'\n Average savings by category (top 5)')
print(df.groupby('category')['total_amount'].mean().sort_values(ascending=False).head(5))

Discount Saved (total_amount) Statistics
Min  savings : ₹8.82
Max  savings : ₹15,295.75
Mean savings : ₹1,516.52

 Average savings by category (top 5)
category
trolley-bag    15295.750000
sherwani        9813.774000
boots           6866.100000
watches         3510.226667
sarees          3401.415909
Name: total_amount, dtype: float64

## Step 7: Save Cleaned Dataset + Summary Report

In [29]:
clean_cols = ['product_id','title','product_description','category',
              'rating','ratings_count','initial_price','discount',
              'final_price','total_amount','seller_name','currency']

df[clean_cols].to_csv('Combined_dataset_cleaned.csv', index=False)
print('Saved: Combined_dataset_cleaned.csv')
print(f'Final shape:{df[clean_cols].shape}')
print()
df[clean_cols].head()

Saved: Combined_dataset_cleaned.csv
Final shape:(1000, 12)

,product_id,title,product_description,category,rating,ratings_count,initial_price,discount,final_price,total_amount,seller_name,currency
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,backpacks,3.8,15,3995,58.0,3995.0,2317.10,Unknown Seller,INR
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,backpacks,4.5,67,2899,35.0,2899.0,1014.65,Unknown Seller,INR
2,17633752,Lavie,Aries Women Pink Mini Backpack,backpacks,4.4,226,2999,65.0,2999.0,1949.35,Unknown Seller,INR
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,backpacks,4.4,1052,1675,52.0,1675.0,871.00,Unknown Seller,INR
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,bath-robe,4.7,12,2899,17.0,2899.0,492.83,Unknown Seller,INR

In [ ]:
# Brief Summary
Dataset: Myntra Combined Product Dataset (Combined_dataset.csv) — 1000 products, 24 columns, 97 categories.
Exploration: Used head(), tail(), shape, dtypes, and describe() to understand the data. Average original price was ₹2,723 with an average discount of 53.8%.
Cleaning Done:

discount (121 missing) → filled with median
seller_name (301 missing) → filled with "Unknown Seller"
what_customers_said (573 missing) → filled with "No Reviews"
videos, seller_information, variations → dropped (50–78% missing)
final_price → cleaned from "₹3,995.00" string format to float
No duplicate rows found

Derived Column: total_amount = initial_price × discount / 100 (average saving: ₹1,516 per product)
Output: Cleaned dataset saved as Combined_dataset_cleaned.csv with 1000 rows and 12 columns.